### PR TITLE
Make compatible with GHC 9.2

### PR DESCRIPTION
**Pull request by johannes-riecken**
It looks like constraint resolution works differently in newer GHC versions. In order to make parsec-free work with my version (9.2.2), I resolved all compilation errors as directly as possible, as I wasn't sure how you would like the MonadReader constraints to be specified for the ParsecF types.

### CODE REVIEW

**Comment by jwiegley** [comment]
This has been published in 3.1.11.7
